update

diff --git a/image2rootfs b/image2rootfs
--- a/image2rootfs
+++ b/image2rootfs
@@ -46,7 +46,7 @@ verbose() {
   [ "$Verbose" = "yes" ] && echo "image2rootfs: ${1:-}" >&2
 }
 ### core functions
-parse_inspect() {               # parse json of inspect output using python
+parse_inspect() {               # json parser using python
   # parse for keys in output of docker|podman|nerdctl inspect.
   # Uses python json parser.
   # $1 String containing inspect output
@@ -101,7 +101,7 @@ EOF
   )"
   echo "$Parserscript" | $Pythonbin - "$@"
 }
-flatten_layers() {              # core work: make on tarball from all layers
+flatten_layers() {              # core work: make one tarball from all layers
   Inspect="$(skopeo inspect --config dir:"$Layerdir")"
   verbose "Output of skopeo inspect --config $Imagesource
 $Inspect"
@@ -120,7 +120,7 @@ $Inspect"
   done
 
   # use base layer as start for rootfs
-  mv "${Layers[1]}" "$Rootfstar"
+  mv "${Layers[1]}" "$Rootfstarball"
 
   for Layer in $(seq 2 $Layercount); do
     note "Processing layer $Layer"
@@ -128,7 +128,7 @@ $Inspect"
     # get a list of files in current layer
     Tarlistcurrent="$(tar -t -f "${Layers[$Layer]}")"
     # get a list of files in current base
-    Tarlistbase="$(tar -t -f "$Rootfstar")"
+    Tarlistbase="$(tar -t -f "$Rootfstarball")"
     
     ## Delete white folder content in base layer
     Deletefolders="$(grep '\.wh\.\.wh\.\.opq' <<< "$Tarlistcurrent")" ||:
@@ -140,7 +140,7 @@ $Inspect"
     # Delete white folders in base layer
     verbose "Folder content to remove in base:
 $(cat $Rmlist)"
-    tar --delete -T $Rmlist -f $Rootfstar
+    tar --delete -T $Rmlist -f $Rootfstarball
     
     # Delete white files in base layer
     Deletefiles="$(grep -v '\.wh\.\.wh\.\.opq' <<< "$Tarlistcurrent" | grep '\.wh\.')" ||:
@@ -155,7 +155,7 @@ $(cat $Rmlist)"
         [ -n "$Line" ] && verbose ">>>> File not found in base layer: $Line"
       }
     done <<< "$Deletefiles"
-    tar --delete -T "$Rmlist" -f "$Rootfstar"
+    tar --delete -T "$Rmlist" -f "$Rootfstarball"
     
     ## Delete white file markers in current layer
     grep '\.wh\.' <<< "$Tarlistcurrent" > "$Rmlist" ||:
@@ -164,11 +164,11 @@ $(cat $Rmlist)"
     tar --delete -T "$Rmlist" -f "${Layers[$Layer]}"
     
     # copy files from current layer to base layer
-    tar --concatenate -f "$Rootfstar" "${Layers[$Layer]}"
+    tar --concatenate -f "$Rootfstarball" "${Layers[$Layer]}"
     rm "${Layers[$Layer]}"
   done
 }
-create_startscript() {          # Create start script and settings store file
+create_startscript() {          # create start script and settings store file
   Cmd="$(       parse_inspect "$Inspect" config Cmd)"
   Entrypoint="$(parse_inspect "$Inspect" config Entrypoint)"
   Env="$(       parse_inspect "$Inspect" config Env)"
@@ -197,9 +197,9 @@ $(cat "$Imagesettings")"
   verbose "generated start script:
 $(cat "$Startscript")"
 
-  tar -r -f "$Rootfstar" -C "$Extractdir" "$(basename "$Imagesettings")" "$(basename "$Startscript")" ||: 
+  tar -r -f "$Rootfstarball" -C "$Extractdir" "$(basename "$Imagesettings")" "$(basename "$Startscript")" ||: 
 #  tar -c -C "$Extractdir" -f "script.tar" "$(basename "$Imagesettings")" "$(basename "$Startscript")"
-#  tar --concatenate --ignore-zeros -C "$Extractdir" -f "$Rootfstar" "script.tar"
+#  tar --concatenate --ignore-zeros -C "$Extractdir" -f "$Rootfstarball" "script.tar"
 }
 ### main
 declare_variables() {
@@ -212,7 +212,7 @@ declare_variables() {
   
   Imagename=""
   Imagesource=""
-  Rootfstar=""
+  Rootfstarball=""
   Targetfile=""
   Pythonbin=""
   Verbose=""
@@ -240,7 +240,6 @@ parse_options() {
   
   [ -z "$Imagesource" ] && error "No image specified. See 'image2rootfs --help'"
   grep -E '^containers-storage:|^dir:|^docker://|^docker-archive|^docker-daemon:|^oci:|^oci-archive:' <<< "$Imagesource" || Imagesource="docker://$Imagesource"
-  verbose "Image source: $Imagesource"
   
   Imagename="$(cut -d: -f2- <<< "$Imagesource")"
   Imagename="${Imagename%:latest}"
@@ -253,15 +252,16 @@ check_dependencies() {
   command -v python  >/dev/null && Pythonbin="python"
   command -v python2 >/dev/null && Pythonbin="python2"
   command -v python3 >/dev/null && Pythonbin="python3"
-  [ -z "$Pythonbin" ] &&          error "No python binary found. Please install python."
+  [ -z "$Pythonbin" ] &&          error "python not found. Please install python (version 2.x or 3.x)."
   command -v skopeo >/dev/null || error "skopeo not found. Please install skopeo."
   command -v tar >/dev/null ||    error "tar not found. Please install tar."
+  command -v gzip >/dev/null ||   error "gzip not found. Please install gzip."
   command -v file >/dev/null ||   error "file not found. Please install file."
 }
 setup_cache() {
-  Rootfstar="rootfs-$Imagebasename.tar"
-  Targetfile="$Rootfsbasedir/$Rootfstar"
-  Rootfstar="$Extractdir/$Rootfstar"
+  Rootfstarball="rootfs-$Imagebasename.tar"
+  Targetfile="$Rootfsbasedir/$Rootfstarball"
+  Rootfstarball="$Extractdir/$Rootfstarball"
   
   mkdir -p "$Extractdir"
   rm -rf "$Extractdir"/* 2>/dev/null ||:
@@ -288,13 +288,15 @@ Mostly the generated rootfs is usable nonetheless."
   # finish
   rm -rf "$Layerdir"
   rm "$Rmlist" "$Startscript" "$Imagesettings"
-  note "Ready
+  
+  note "Ready.
 To provide a rootfs for 'x11docker --backend=proot $Imagebasename',
 please run:
   mkdir -p $Rootfsbasedir/$Imagebasename
-  tar -x -f $Rootfstar -C $Rootfsbasedir/$Imagebasename"
+  tar -C $Rootfsbasedir/$Imagebasename" -x -f $Rootfstarball
+  
   note "Generated rootfs tarball:"
-  echo "$Rootfstar"
+  echo "$Rootfstarball"
 }
 main "$@"
 exit 0
